### ISSUE TITLE
Login to Developer Account gives redirect loop

### ISSUE THREAD

**Issue by JordanMG13** [canonical/snapcraft.io#3838] opened 2022-01-07 16:31 UTC
A customer reported a problem being able to login to their Developer Account page.

### Expected behavior
- Click on Developer Account
- Login
- After successful authentication, be brought to https://snapcraft.io/snaps

### Steps to reproduce the problem
- Have an account with the customer
- Go to https://snapcraft.io
- Click on Developer Account
- Get an infinite redirect login loop

### Attempted fixes
- Opening browser in private window to see if issue was cookie/cache related (Result: same problem as above)

### Specs

- _URL:_ https://snapcraft.io
- _Operating system:_ Ubuntu 16.04
- _Browser:_Firefox and Safari

**Comment by jkfran** [comment] 2022-01-11 09:21
Hi @JordanMG13 

Can you confirm if the customer is still having this issue? We can't reproduce it

**Comment by JordanMG13** [comment] 2022-01-11 15:41
@jkfran Checking in with them now.

**Comment by jkfran** [comment] 2022-01-14 11:07
Hi @JordanMG13, did they get back to you?

**Comment by jkfran** [comment] 2022-01-18 11:26
There is a similar bug reported recently for Ubuntu SSO:
https://bugs.launchpad.net/canonical-identity-provider/+bug/1895734/

I'll try to keep you posted.

**Comment by JordanMG13** [comment] 2022-01-18 19:32
@jkfran They have not yet, I can ping them again. And thanks for the info!

**Comment by JordanMG13** [comment] 2022-01-19 17:47
@jkfran To confirm, they are still experiencing this issue.

**Comment by jkfran** [comment] 2022-01-20 14:53
@maxiberta, do you know when [your fix](https://code.launchpad.net/~maxiberta/canonical-identity-provider/+git/canonical-identity-provider/+merge/414316) is going to land on production?

**Comment by maxiberta** [comment] 2022-01-20 16:11
@jkfran we're planning to do it today.

**Comment by maxiberta** [comment] 2022-01-20 19:36
The Ubuntu SSO update is now in production.
Please delete all related cookies so that they're updated correctly.

**Comment by JordanMG13** [comment] 2022-01-20 19:55
I will tell them to try this, thanks!

**Comment by JordanMG13** [comment] 2022-01-21 23:53
It looks like the customer is still having this issue, even after wiping their cookies.

**Comment by JordanMG13** [comment] 2022-01-24 16:30
@jkfran Will do!

**Comment by jameinel** [comment] 2022-01-25 12:44
I also got the redirect from one of my browsers running Firefox 96.0.1. With 96.0.2 it doesn't redirect and does login. login-beta did work and didn't have the strange redirect that you see with login. Both still took ~30s before it loaded a page, without any other indication that it was working.

**Comment by jkfran** [comment] 2022-01-25 14:32
I believe this issue has been solved with https://github.com/canonical-web-and-design/snapcraft.io/pull/3869. I am going to close this issue but please reopen if needed.

**Comment by JordanMG13** [comment] 2022-01-31 15:16
@jkfran Got this response from the customer when trying the https://snapcraft.io/login-beta link:

In Firefox, I get into the same redirect loop. On a private window in Safari, I got an Internal Server Error page. On Firefox private mode, If I Click the SSO button, it just brings me back to the same page.

**Comment by JordanMG13** [comment] 2022-02-14 16:46
Just checking if there has been any progress on this issue?

Thanks!

**Comment by JordanMG13** [comment] 2022-02-22 22:38
> Just checking if there has been any progress on this issue?
> 
> Thanks!

bump

**Comment by jkfran** [comment] 2022-02-23 10:03
Hi @JordanMG13 we are not getting any reports of issues with the authentication apart from you which is very strange.

Could you ask them to send us a screenshot of the results that they get on this site https://samesite-sandbox.glitch.me/

Thank you!

**Comment by JordanMG13** [comment] 2022-02-23 15:08
@jkfran Will do!

**Comment by JordanMG13** [comment] 2022-03-06 16:17
Here are the results:

Safari:
![Safari](https://user-images.githubusercontent.com/91559220/156931666-3b509f5d-3c6b-43c0-9c92-352051108ba9.png)

Firefox:
![Firefox](https://user-images.githubusercontent.com/91559220/156931668-aab93811-5bbe-4e5a-8115-97ecf1366b20.png)

**Comment by JordanMG13** [comment] 2022-03-11 22:32
@jkfran Uploaded screenshots

**Comment by jkfran** [comment] 2022-03-15 09:35
Hi @JordanMG13 

We are confident that are no reports of issues with the authentication on snapcraft.io. Could it be possible that they have a problem with Ubuntu SSO instead of snapcraft.io? Could they try to sign in on https://dashboard.snapcraft.io/ or https://ubuntu.com/login

**Comment by JordanMG13** [comment] 2022-03-15 21:35
I will check with them and update this issue

**Comment by JordanMG13** [comment] 2022-03-15 21:37
@jkfran They did let me know awhile back that https://dashboard.snapcraft.io/ is not effected. I will ask about ubuntu.com/login

**Comment by jkfran** [comment] 2022-03-16 09:05
> @jkfran They did let me know awhile back that https://dashboard.snapcraft.io/ is not effected. I will ask about https://ubuntu.com/login

A colleague also mention this solution for a similar problem: https://github.com/canonical-web-and-design/snapcraft.io/issues/1040#issuecomment-420333343

**Comment by JordanMG13** [comment] 2022-04-04 16:18
Thanks @jkfran! Still haven't heard back from the customer after asking them to double check they had a username set,... closing for now...

**Comment by JordanMG13** [comment] 2022-10-26 20:28
Hello!

Just wanting to reopen this case, as the customer has gotten back to me and is still having this issue. They also do have a username set in SSO.

**Comment by jkfran** [comment] 2022-10-28 14:24
Hi @JordanMG13, I have seen that @Roadmaster was taking a look into it. Something might be wrong with their SSO account. Please let us know if you need anything from us.

**Comment by JordanMG13** [comment] 2023-01-23 15:58
@Lukewh just checking, is there any progress on this issue by chance?

**Comment by Lukewh** [comment] 2023-01-23 16:52
> @Lukewh just checking, is there any progress on this issue by chance?

Still doing a bit of back and forth with EJ @JordanMG13, I'll update this issue when things are sorted. Sorry for the delays, timezones slow things down somewhat!

**Comment by JordanMG13** [comment] 2023-01-23 16:53
> > @Lukewh just checking, is there any progress on this issue by chance?
> 
> Still doing a bit of back and forth with EJ @JordanMG13, I'll update this issue when things are sorted. Sorry for the delays, timezones slow things down somewhat!

No worries! Just checking in :smile:

**Comment by JordanMG13** [comment] 2023-02-14 16:56
@Lukewh Hello! Just checking in again for any updates :smile:

**Comment by Lukewh** [comment] 2023-02-16 14:33
Hi @JordanMG13, I've been working with EJ, but still haven't found a root cause.

**Comment by JordanMG13** [comment] 2023-02-27 19:14
@Lukewh Hello again! Apologies for the repeated pings, just checking in again about this issue.

**Comment by JordanMG13** [comment] 2023-03-20 19:43
Hello!

Any updates on this issue by chance?

**Comment by Lukewh** [comment] 2023-03-21 11:44
Still no fix for this specific issue unfortunately. I am looking into another brand store issue at the moment that prevents viewers seeing stores. It may be related, I'll update this issue when that work goes live.

**Comment by JordanMG13** [comment] 2023-03-21 14:54
Appreciate it!

**Comment by Lukewh** [comment] 2023-03-22 13:33
@JordanMG13 I've done some refactoring to how stores are fetched – can you see if this has resolved the issue for EJ? Thanks

**Comment by JordanMG13** [comment] 2023-04-05 21:43
@Lukewh Hello again! Unfortunately, no, this did not resolve the issue for them still. They have attached a Firebug report if you need that as well

**Comment by lmoureaux** [comment] 2023-04-09 18:32
I'm affected by a similar with two newly created accounts. I'm using Firefox on Ubuntu but the same issue appears with Chromium. The password prompt is never shown and the following requests are repeated over and over again:
![image](https://user-images.githubusercontent.com/22327575/230789594-1dd36c48-33c4-4b8f-9b2d-1259624c911b.png)
Login works on `ubuntu.com` and `dashboard.snapcraft.io`.

**Comment by Lukewh** [comment] 2023-04-13 08:18
Still an issue for some users

**Comment by JordanMG13** [comment] 2023-05-08 18:41
Hey @Lukewh! Any updates by chance on this issue?

**Comment by Lukewh** [comment] 2023-05-17 10:15
Sorry, @JordanMG13 this is still an ongoing investigation. I'm creating a plan to outline how we move forward with figuring this out, as we need to identify the hole in our visibility!

**Comment by JordanMG13** [comment] 2023-05-17 14:06
Sounds good! Appreciate your investigations and updates!

**Closed** 2023-06-09 09:42 UTC
