### ISSUE TITLE
RFE: New/Updated/Featured snaps discovery issue

### ISSUE THREAD

**Issue by keshavbhatt** [canonical/snapcraft.io#4276] opened 2023-06-02 14:00 UTC
### Expected behaviour
Snapcraft store page (https://snapcraft.io/store) shows the following sections:
- Include a section for Recently Published Snaps, showcasing the latest snaps that publishers have released.
- Add a section for Recently Updated Snaps, highlighting snaps that have been recently updated.
- Enhance the Featured Snaps section by ensuring it receives regular updates.

Please find more information about this RFE here: https://forum.snapcraft.io/t/show-latest-updated-snaps-in-snapcraft-io/35442

### Steps to reproduce the problem
Visit https://snapcraft.io/store and try to discover:
- new snaps
- recently updated snaps
- featured snaps (there is a section for this but is static, never saw it updating)

### Specs

- _URL:_ https://snapcraft.io/store
- _Operating system:_ Ubuntu
- _Browser:_ Chrome

**Comment by Lukewh** [comment] 2024-02-13 10:19
Duplicate of https://github.com/canonical/snapcraft.io/issues/2921

**Closed by Lukewh** 2024-02-13 10:19 UTC
