### ISSUE TITLE
website Internal Server Error Please try again later all status in green on status page

### ISSUE THREAD

**Issue by andykimpe** [canonical/snapcraft.io#4526] opened 2024-02-09 13:56 UTC
please solve actual website snapcraft.io return this error

Internal Server Error
Please try again later

You can check the service status at [status.snapcraft.io](https://status.snapcraft.io/).

If the problem persists please check the Snapcraft [forum](https://forum.snapcraft.io/) or [report an issue](https://github.com/canonical-web-and-design/snapcraft.io/issues/new).

all status in green on the status page please solve

**Comment by steverydz** [comment] 2024-02-09 14:02
Hi @andykimpe. Can you paste the URL you were trying to access or was this the homepage?

**Comment by andykimpe** [comment] 2024-02-09 14:35
I had this problem on all pages including the forum page with the exception of the status page

in other words all pages

https://snapcraft.io/*

https://forum.snapcraft.io/*

including home pages

but here it is again

It's up to you to see why this happened and make sure that it doesn't happen again afterwards. I can't find out more. It's up to you to see what happened in the logs.

its displayed for about 10 minutes

**Comment by Lukewh** [comment] 2024-02-13 10:04
is this still an issue @andykimpe? There's nothing we can see in our logs that would be causing this. There were some infrastructure issues in the last few days that may have been the cause.

**Comment by PaSharks9** [comment] 2024-04-10 07:31
@Lukewh Yes i think it is. I'm following the Ubuntu Core tutorial so i I signed up on Ubuntu One and from my CLI I ran the`snapcraft login` command without being able to authenticate. So i just tryed to login in Canonical Snapcraft and after agreed the privacy stuff i got the Internal Server Error. Could be the same error?

**Comment by Lukewh** [comment] 2024-04-11 15:48
We believe this is now fixed. If the problem persists please do let us know!

**Closed by Lukewh** 2024-04-11 15:48 UTC
Labels: Being investigated
