### ISSUE TITLE
Show new snaps and updated snaps on main page

### ISSUE THREAD

**Issue by alculete** [canonical/snapcraft.io#4380] opened 2023-08-14 14:07 UTC
### Expected behaviour
The home page shows recent and updated snaps, featured snaps show the most downloaded or most searched, or any other algorithm that shows different categories of snaps and updates weekly (or at least monthly).
Featured snaps have been the same for more than a year.

### Steps to reproduce the problem
Just go to the Snapcraft home page

### Specs

- _URL:_ https://snapcraft.io/
- _Operating system:_ ubuntu 22.04.3

**Comment by Lukewh** [comment] 2024-02-13 10:19
Duplicate of https://github.com/canonical/snapcraft.io/issues/2921

**Closed by Lukewh** 2024-02-13 10:19 UTC
Labels: Being investigated
